import { NextRequest, NextResponse } from 'next/server';
import nodemailer from 'nodemailer';
import { requireAuth } from '@/lib/auth';

async function handler(request: NextRequest) {
  try {
    const { topic } = await request.json();

    if (!topic) {
      return NextResponse.json(
        { success: false, error: 'Topic is required' },
        { status: 400 }
      );
    }

    // Generate post content
    const openrouterApiKey = process.env.OPENROUTER_API_KEY;
    const model = process.env.OPENROUTER_MODEL || 'openai/gpt-4o-mini';

    if (!openrouterApiKey) {
      return NextResponse.json(
        { success: false, error: 'OpenRouter API key not configured' },
        { status: 500 }
      );
    }

    const aiResponse = await fetch('https://openrouter.ai/api/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${openrouterApiKey}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        model,
        messages: [
          {
            role: 'system',
            content: 'You are a professional LinkedIn content creator. Create engaging, professional LinkedIn posts in plain text. Use line breaks, emojis, and clear structure. No HTML, no Markdown formatting. Keep it concise and impactful (200-300 words max).'
          },
          {
            role: 'user',
            content: `Create a LinkedIn post about: ${topic}`
          }
        ],
      }),
    });

    if (!aiResponse.ok) {
      throw new Error('AI generation failed');
    }

    const aiData = await aiResponse.json();
    const postContent = aiData.choices[0].message.content;

    // Send email
    const smtpHost = process.env.SMTP_HOST;
    const smtpPort = parseInt(process.env.SMTP_PORT || '587');
    const smtpUser = process.env.SMTP_USER;
    const smtpPassword = process.env.SMTP_PASSWORD;
    const emailFrom = process.env.EMAIL_FROM || smtpUser;
    const emailTo = process.env.EMAIL_TO;

    if (!smtpHost || !smtpUser || !smtpPassword || !emailTo) {
      return NextResponse.json(
        {
          success: false,
          error: 'SMTP configuration incomplete. Set SMTP_HOST, SMTP_USER, SMTP_PASSWORD, EMAIL_TO'
        },
        { status: 500 }
      );
    }

    const transporter = nodemailer.createTransport({
      host: smtpHost,
      port: smtpPort,
      secure: smtpPort === 465,
      auth: {
        user: smtpUser,
        pass: smtpPassword,
      },
    });

    const htmlContent = `
      <!DOCTYPE html>
      <html>
      <head>
        <style>
          body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; }
          .container { max-width: 600px; margin: 0 auto; padding: 20px; }
          .header { background: #0077b5; color: white; padding: 20px; border-radius: 5px 5px 0 0; }
          .content { background: #f9f9f9; padding: 20px; border: 1px solid #ddd; }
          .post { background: white; padding: 20px; border-radius: 5px; white-space: pre-wrap; }
          .footer { text-align: center; padding: 20px; color: #666; font-size: 12px; }
        </style>
      </head>
      <body>
        <div class="container">
          <div class="header">
            <h1>LinkedIn Post Ready</h1>
          </div>
          <div class="content">
            <h2>Topic: ${topic}</h2>
            <div class="post">${postContent}</div>
          </div>
          <div class="footer">
            <p>Generated by Coolify Button App</p>
          </div>
        </div>
      </body>
      </html>
    `;

    const info = await transporter.sendMail({
      from: emailFrom,
      to: emailTo,
      subject: `LinkedIn Post: ${topic}`,
      text: `Topic: ${topic}\n\n${postContent}`,
      html: htmlContent,
    });

    return NextResponse.json({
      success: true,
      message: 'Post generated and sent via email',
      data: {
        content: postContent,
        messageId: info.messageId,
      },
    });

  } catch (error: any) {
    console.error('Generate post email error:', error);
    return NextResponse.json(
      {
        success: false,
        error: error.message || 'Failed to generate and send post'
      },
      { status: 500 }
    );
  }
}

export const POST = requireAuth(handler);
